import React from "react";
import Head from "next/head";

type LayoutProps = {
	children: React.ReactNode;
	title: string;
};

export default function Container() {
	return (
		<>
			<Head>
				<title>Create Next </title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
		</>
	);
}
